"""empty message

Revision ID: 58af5a4a48ed
Revises: 98aedd902507
Create Date: 2023-11-06 23:47:40.928972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58af5a4a48ed'
down_revision = '98aedd902507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peoples', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peoples', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
